services:
  go:
    build: .
    ports:
      - "8080:8080"
    working_dir: /app
    tty: true
    volumes:
      - .:/app
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dockertest_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dockertest_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
